---
- name: installing pip3
  apt:
    name: python3-pip
    state: present
  become: yes

- name: installing boto
  pip:
    name: boto
    executable: pip3
    state: present
  become: yes

- name: installing boto
  pip:
    name: boto3
    executable: pip3
    state: present
  become: yes

