---
 - name: Create the file repository configuration
   shell: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

 - name: Import the repository signing key
   apt_key:
     url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
     state: present

 - name: Run the equivalent of "apt-get update" as a separate step
   apt:
     update_cache: yes

 - name: Install version-12 of Progressql
   apt:
     name: "{{ item }}"
     state: present
     update_cache: true
   loop:
     - postgresql-12
     - postgresql-client-12
     - postgresql-12
     - postgresql-contrib-12
     - libpq-dev
     - postgresql-server-dev-12

 - name: Create a new database with name "acme"
   postgresql_db:
     name: postgress_db

 - name: Connect to acme database and set user's password with no expire date
   postgresql_user:
     db: postgress_db
     name: thinknyx
     password: Thinknyx@07
     priv: "CONNECT/products:ALL"
     expires: infinity

 - name: Create a new schema with name acme in test database
   postgresql_schema:
     db: postgress_db
     name: thinknyx_schema

 - name: Dump an existing database to a file
   postgresql_db:
     name: postgress_db
     state: dump
     target: /tmp/dump.sql
