---
 - name: Create the file repository configuration
   shell: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

 - name: Import the repository signing key
   apt_key:
     url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
     state: present
 
 - name: install python3-pip
   apt:
     name: python3-pip
     state: present

 - name: Run the equivalent of "apt-get update" as a separate step
   apt:
     update_cache: yes

 - name: Install version-12 of Progressql
   apt:
     name: "{{ item }}"
     state: present
     update_cache: true
   loop:
     - postgresql-12
     - postgresql-client-12
     - postgresql-12
     - postgresql-contrib-12
     - libpq-dev
     - postgresql-server-dev-12
 
 - name: Make sure psycopg2 is installed
   pip:
    name: psycopg2
    state: present

 - name: Create a new database with name "acme"
   become: true
   become_user: postgres
   postgresql_db:
     name: "{{ db_name }}"

 - name: Connect to acme database and set user's password with no expire date
   become: true
   become_user: postgres
   postgresql_user:
     db: "{{ db_name }}"
     name: "{{ user_name }}"
     password: "{{ password }}"
#    priv: "CONNECT/products:ALL"
     priv: ALL
     state: present
     expires: infinity

 - name: Create a new schema with name acme in test database
   become: true
   become_user: postgres
   postgresql_schema:
     db: "{{ db_name }}"
     name: "{{ schema_name }}"

 - name: Dump an existing database to a file
   become: true
   become_user: postgres
   postgresql_db:
     name: "{{ db_name }}"
     state: dump
     target: /tmp/dump.sql
